[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"

# Use the Netlify Next.js plugin
[[plugins]]
  package = "@netlify/plugin-nextjs"

# Force the build to use our configuration, not the one from the UI
[build.processing]
  skip_processing = false

# Handle client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 